spring.application.name=biblioteca-gp5

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.flyway.enabled=true

spring.jpa.hibernate.ddl-auto=none

spring.jpa.properties.hibernate.format_sql=true

api.security.token = ${JWT_SECRET:my-secret-key}

spring.mail.host=smtp.gmail.com
spring.mail.port=465

spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smptp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true

logging.level.org.hibernate.SQL=DEBUG
loggin.level.org.hibernate.orm.jdbc.bind=TRACE

gutendex.base-url=https://gutendex.com

app.storage.path=storage

app.files.base-url=${URL_FILES}
