CREATE TABLE categories(
	id_categories BINARY(16) UNIQUE NOT NULL,
    name VARCHAR (100) UNIQUE NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    PRIMARY KEY(id_categories)
);